@startuml edu.utdallas.davisbase.storage.DataFileAccessor

interface java.nio.Channel
interface java.util.Iterator

' java.nio.Channel -[hidden]- java.util.Iterator

package edu.utdallas.davisbase.storage {

  interface TableRecord {
    '// TODO Declare TableRecord members
  }

  interface IndexRecord {
    '// COMBAK Declare IndexRecord members
  }

  java.util.Iterator <|.. TableFileIterator
  TableRecord <.. TableFileIterator : <<use>>
  interface TableFileIterator {
    +add(:TableRecord)
    +/hasNext(): boolean
    +/next(): TableRecord
    +nextRowId(): RowId
    +remove()
    +set(:TableRecord)
  }

  java.util.Iterator <|.. IndexFileIterator
  IndexRecord <.. IndexFileIterator : <<use>>
  interface IndexFileIterator {
    '// COMBAK Declare IndexFileIterator members
  }


  java.nio.Channel <|.. DataFileAccessor
  abstract DataFileAccessor {
    {field} #:RandomAccessFile
    #<<create>> DataFileAccessor(:RandomAccessFile)
    +/close()
    +/isOpen(): boolean
  }

  TableFileIterator <|.. TableFileAccessor
  DataFileAccessor <|-- TableFileAccessor
  class TableFileAccessor {
    ~<<create>> TableFileAccessor(:RandomAccessFile)
    '// TODO Declare TableFileAccessor members
  }

  IndexFileIterator <|.. IndexFileAccessor
  DataFileAccessor <|-- IndexFileAccessor
  class IndexFileAccessor {
    ~<<create>> IndexFileAccessor(:RandomAccessFile)
    '// COMBAK Declare IndexFileAccessor members
  }
}

hide interface fields

hide java.nio.Channel members
hide java.util.Iterator members

@enduml
