@startuml edu.utdallas.davisbase.storage.Storage

package edu.utdallas.davisbase.storage {

  class Storage {
    #configuration: Storage.Configuration
    #state: Storage.State
    #<<create>> Storage(configuration: Storage.Configuration, state: Storage.State)
    +getDataFiles(): DataFileInfo[0..*]
    +openTable(tableName: String): TableFileAccessor
    +openIndex(tableName: String, columnName: String): IndexFileAccessor
  }

  Storage o-- Configuration
  Storage +-- Configuration
  class Configuration {
    +dataDirectoryName: String = "data"
    +tableFileExtension: String = "tbl"
    +indexFileExtension: String = "ndx"
    +catalogTablesTableName: String = "davisbase_tables"
    +catalogColumnsTableName: String = "davisbase_columns"
  }
  hide Configuration methods

  Storage *-- State
  Storage +-- State
  class State {
    {field} +dataDirectory: String = System.getProperty("user.dir")
    {field} +openedTableAccessors: Map<fileName: String, TableFileAccessor> = new Map<>()
    {field} +openedIndexAccessors: Map<fileName: String, IndexFileAccessor> = new Map<>()
  }
  hide State methods

}
@enduml
